version: '3.8'

services:
  nuxt-vps-demo:
    image: lokyiec/nuxt-vps-demo:latest
    env_file:
      - .env
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vps-demo.rule=Host(`${VPS_DEMO_HOSTNAME}`)"
      - "traefik.http.routers.vps-demo.entrypoints=websecure"
      - "traefik.http.routers.vps-demo.tls=true"
      - "traefik.http.routers.vps-demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.vps-demo.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-network"
    deploy:
      restart_policy:
        condition: any

networks:
  traefik-network:
    external: true