version: '3.8'

services:
  nuxt-vps-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: lokyiec/nuxt-vps-demo:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vps-demo.rule=Host(`${VPS_DEMO_HOSTNAME}`)"
      - "traefik.http.routers.vps-demo.entrypoints=websecure"
      - "traefik.http.routers.vps-demo.tls=true"
      - "traefik.http.routers.vps-demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.vps-demo.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-network"

networks:
  traefik-network:
    external: true
